using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FireBehavior : MonoBehaviour
{
    private PlayerController playerController;

    // Start is called before the first frame update
    void Start()
    {
        playerController = GameObject.Find("Player").GetComponent<PlayerController>();
    }
    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.gameObject.CompareTag("Water"))
        {
            playerController.addPoints(1);
            Extinguish();
        }
    }

    void Extinguish()
    {
        
        Destroy(gameObject);  // Destr√≥i o objeto de fogo
    }
}
